name: food_delivery
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
   sdk: ">=3.4.0 <4.0.0"

dependencies:
   flutter:
      sdk: flutter
   get: ^4.6.6
   dots_indicator: ^3.0.0
   persistent_bottom_nav_bar: ^6.2.1
   flutter_screenutil: ^5.9.3
   readmore: ^3.0.0
   shared_preferences: ^2.3.2
   intl: ^0.19.0
   dio: ^5.7.0
   firebase_core: ^3.6.0
   firebase_database: ^11.1.4
   firebase_auth: ^5.3.1
   cloud_firestore: ^5.4.4
   provider: ^6.0.0
   equatable: ^2.0.5
   uuid: ^4.5.1
   cupertino_icons: ^1.0.6
   font_awesome_flutter: ^10.4.0
   pdf: ^3.11.1
   printing: ^5.13.4
   flutter_paypal_checkout: ^1.0.1
   flutter_image_compress: ^2.3.0

   cloudinary_flutter: ^1.2.0
   cloudinary_url_gen: ^1.6.0

   google_sign_in: ^6.2.2

   image_picker: ^1.1.2
   file_picker: ^5.2.7
   path_provider: ^2.1.5
   permission_handler: ^10.2.0
   crypto: ^3.0.6
   http: ^0.13.6

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^5.0.0
   firebase_auth_platform_interface: ^7.0.5
   firebase_core_platform_interface: ^5.0.0

flutter:
   uses-material-design: true
   assets:
      - assets/fonts/
      - assets/images/
   fonts:
      - family: Mulish
        fonts:
           - asset: assets/fonts/MULISH-BLACK.TTF
             weight: 900
           - asset: assets/fonts/MULISH-BLACKITALIC.TTF
             weight: 900
             style: italic
           - asset: assets/fonts/MULISH-EXTRABOLD.TTF
             weight: 800
           - asset: assets/fonts/MULISH-EXTRABOLDITALIC.TTF
             weight: 800
             style: italic
           - asset: assets/fonts/MULISH-BOLD.TTF
             weight: 700
           - asset: assets/fonts/MULISH-BOLDITALIC.TTF
             weight: 700
             style: italic
           - asset: assets/fonts/MULISH-SEMIBOLD.TTF
             weight: 600
           - asset: assets/fonts/MULISH-SEMIBOLDITALIC.TTF
             weight: 600
             style: italic
           - asset: assets/fonts/MULISH-MEDIUM.TTF
             weight: 500
           - asset: assets/fonts/MULISH-MEDIUMITALIC.TTF
             weight: 500
             style: italic
           - asset: assets/fonts/MULISH-REGULAR.TTF
             weight: 400
           - asset: assets/fonts/MULISH-ITALIC.TTF
             weight: 400
             style: italic
           - asset: assets/fonts/MULISH-LIGHT.TTF
             weight: 300
           - asset: assets/fonts/MULISH-LIGHTITALIC.TTF
             weight: 300
             style: italic
           - asset: assets/fonts/MULISH-EXTRALIGHT.TTF
             weight: 200
           - asset: assets/fonts/MULISH-EXTRALIGHTITALIC.TTF
             weight: 200
             style: italic
